services:
  xpensegem-be:
    build: .
    container_name: ekady_xpensegem-be
    ports:
      - 3333:3333
    environment:
      - API_PORT=$API_PORT
      - API_PREFIX=$API_PREFIX
      - API_VERSION=$API_VERSION
      - API_CORS_ORIGIN=$API_CORS_ORIGIN
      - URL_CLIENT=$URL_CLIENT
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - LOGGER_HTTP_WRITE_INTO_FILE=$LOGGER_HTTP_WRITE_INTO_FILE
      - LOGGER_HTTP_WRITE_INTO_CONSOLE=$LOGGER_HTTP_WRITE_INTO_CONSOLE
      - LOGGER_HTTP_MAX_SIZE=$LOGGER_HTTP_MAX_SIZE
      - LOGGER_HTTP_MAX_FILES=$LOGGER_HTTP_MAX_FILES
      - LOGGER_SYSTEM_WRITE_INTO_FILE=$LOGGER_SYSTEM_WRITE_INTO_FILE
      - LOGGER_SYSTEM_WRITE_INTO_CONSOLE=$LOGGER_SYSTEM_WRITE_INTO_CONSOLE
      - LOGGER_SYSTEM_MAX_SIZE=$LOGGER_SYSTEM_MAX_SIZE
      - LOGGER_SYSTEM_MAX_FILES=$LOGGER_SYSTEM_MAX_FILES
      - MAX_SIZE_PER_FILE_UPLOAD=$MAX_SIZE_PER_FILE_UPLOAD
      - MAX_NUMBER_FILE_UPLOAD=$MAX_NUMBER_FILE_UPLOAD
      - JWT_TOKEN_TYPE=$JWT_TOKEN_TYPE
      - JWT_SECRET=$JWT_SECRET
      - JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
      - JWT_EXPIRES_IN=$JWT_EXPIRES_IN
      - JWT_REFRESH_EXPIRES_IN=$JWT_REFRESH_EXPIRES_IN
      - JWT_COOKIE_EXPIRES_IN=$JWT_COOKIE_EXPIRES_IN
      - GOOGLE_OAUTH_CLIENT=$GOOGLE_OAUTH_CLIENT
      - JWT_SECRET_GOOGLE_OAUTH=$JWT_SECRET_GOOGLE_OAUTH
      - RESET_PASSWORD_TOKEN_EXPIRES_IN=$RESET_PASSWORD_TOKEN_EXPIRES_IN
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_USERNAME=$EMAIL_USERNAME
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - EMAIL_IDENTITY=$EMAIL_IDENTITY
      - GRAVATAR_URL=$GRAVATAR_URL
      - FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY
      - FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      - FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL
      - FIREBASE_JSON=$FIREBASE_JSON
      - AWS_CREDENTIAL_KEY=$AWS_CREDENTIAL_KEY
      - AWS_CREDENTIAL_SECRET_KEY=$AWS_CREDENTIAL_SECRET_KEY
      - AWS_S3_REGION=$AWS_S3_REGION
      - AWS_S3_BUCKET=$AWS_S3_BUCKET
      - AWS_S3_BASE_URL=$AWS_S3_BASE_URL
      - USER_DEMO_PASSWORD=$USER_DEMO_PASSWORD
      - ENABLE_SWAGGER=$ENABLE_SWAGGER
      - ENABLE_FIREBASE=$ENABLE_FIREBASE
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '5432:5432'